const testArray = [
  {
    id        : 1,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 2,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 3,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 4,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 5,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 6,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 7,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 8,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 9,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 10,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 11,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 12,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 13,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/parallax2.jpg",
  },
  {
    id        : 14,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 15,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 16,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 17,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/image-2x.png",
  },
  {
    id        : 18,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 19,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 20,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/parallax2.jpg",
  },
  {
    id        : 11,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 12,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 13,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 14,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 15,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 16,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 17,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 81,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 19,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 110,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 111,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 112,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 113,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/parallax2.jpg",
  },
  {
    id        : 114,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 115,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 116,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 117,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/image-2x.png",
  },
  {
    id        : 118,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://placeimg.com/500/300/nature",
  },
  {
    id        : 119,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/chicken-salad.jpg",
  },
  {
    id        : 120,
    title     : "name of the Product",
    details   : "info about the Product",
    category  : "category of product [gaz | water | sanitation | all ]",
    img       : "https://cdn.quasar.dev/img/parallax2.jpg",
  },
];

export default testArray;
